springdoc:
  swagger-ui:
    use-root-path: true
server.port: 9000
domain:
  name: http://144.24.65.52:${server.port}
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/rgt
    username: sa
    password: